export const GET_USERS= {
    GET_USERS_PENDING: "GET_USERS_PENDING",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_ERROR: "GET_USERS_ERROR"
};

export const DELETE_USER = {
    DELETE_USER_PENDING: "DELETE_USER_PENDING",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_ERROR: "DELETE_USER_ERROR"
};

export const ADD_USER = {
    ADD_USER_PENDING: "ADD_USER_PENDING",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_ERROR: "ADD_USER_ERROR"
};

export const EDIT_USER ={
    EDIT_USER_PENDING: "EDIT_USER_PENDING",
    EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
    EDIT_USER_ERROR: "EDIT_USER_ERROR"
};

export const GET_VIDEOS = {
    GET_VIDEOS_PENDING: "GET_VIDEOS_PENDING",
    GET_VIDEOS_SUCCESS: "GET_VIDEOS_SUCCESS",
    GET_VIDEOS_ERROR: "GET_VIDEOS_ERROR"
};

export const SET_VIDEO_NAME ={
    SET_VIDEO_NAME:"SET_VIDEO_NAME"
};